<a href="https://colab.research.google.com/github/muhxz3/Ecommerce-Sales-Analysis/blob/main/Day8(Pandas_continued).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data selecting, extracting and slicing**

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "name": ['A','B','C','D'],
    "marks": [88,76,92,98],
    "city": ["Del","Pun","Koc","Mum"]
})

print(df)

  name  marks city
0    A     88  Del
1    B     76  Pun
2    C     92  Koc
3    D     98  Mum

In [ ]:
print(df["name"])

0    A
1    B
2    C
3    D
Name: name, dtype: object

In [ ]:
print(df[["name","city"]])

  name city
0    A  Del
1    B  Pun
2    C  Koc
3    D  Mum

**.loc and .iloc**<br>
.loc - label based<br>
.iloc - index position based

In [ ]:
# df.loc[rowlabel, columnlabel]
df.loc[1]

name       B
marks     76
city     Pun
Name: 1, dtype: object

In [ ]:
df.loc[1,"name"]

'B'

In [ ]:
df.loc[2,"city"]

'Koc'

In [ ]:
df.iloc[0]

name       A
marks     88
city     Del
Name: 0, dtype: object

**Slicing**

In [ ]:
df.loc[1:3]

  name  marks city
1    B     76  Pun
2    C     92  Koc
3    D     98  Mum

In [ ]:
df = pd.DataFrame({
    "name": ['Arun','Muhaz', 'Arjun']},
    index = ['A','B','C']
)

df.loc["B":"C"]

    name
B  Muhaz
C  Arjun

**.loc with Filtering**

In [ ]:
df = pd.DataFrame({
    "name": ['A','B','C','D'],
    "marks": [88,76,92,98],
    "city": ["Del","Pun","Koc","Mum"]
})

df.loc[df["marks"]>90]

  name  marks city
2    C     92  Koc
3    D     98  Mum

**.iloc**

In [ ]:
df.iloc[0]

name       A
marks     88
city     Del
Name: 0, dtype: object

In [ ]:
"""
While performing slicing .iloc exclude the stop index
but .loc includes it.
"""
df.iloc[1:3] # slicing

  name  marks city
1    B     76  Pun
2    C     92  Koc

**Row + Column**

In [ ]:
df.iloc[0,2] # df.iloc[row_index, col_index]

'Del'

In [ ]:
df["name"]=="A"

0     True
1    False
2    False
3    False
Name: name, dtype: bool

In [ ]:
df[(df["name"] == 'A') & (df["city"] == 'Del')]

  name  marks city
0    A     88  Del

In [ ]:
df[(df["name"] == 'A') | (df["name"] == 'B')]

  name  marks city
0    A     88  Del
1    B     76  Pun

In [ ]:
df[~(df["name"] == 'B')]

  name  marks city
0    A     88  Del
2    C     92  Koc
3    D     98  Mum

**.isin()**

In [ ]:
df["name"].isin(['A','C'])

0     True
1    False
2     True
3    False
Name: name, dtype: bool

In [ ]:
df[df["name"].isin(['A','C'])]

  name  marks city
0    A     88  Del
2    C     92  Koc

**.between**

In [ ]:
df[df["marks"].between(90,100)]

  name  marks city
2    C     92  Koc
3    D     98  Mum

**.str**<br>
.contains()<br>
.startswith()<br>
.endswith()<br>
.lower()

In [ ]:
df["name"].str.lower()

0    a
1    b
2    c
3    d
Name: name, dtype: object

In [ ]:
df[df["name"].str.contains("A")]

  name  marks city
0    A     88  Del

In [ ]:
df[df["city"].str.startswith("D")]

  name  marks city
0    A     88  Del

In [ ]:
df[df["city"].str.endswith("n")]

  name  marks city
1    B     76  Pun

**Sorting**<br>
sort_values()

In [ ]:
df.sort_values("city")

  name  marks city
0    A     88  Del
2    C     92  Koc
3    D     98  Mum
1    B     76  Pun

In [ ]:
df.sort_values("city",ascending=False)

  name  marks city
1    B     76  Pun
3    D     98  Mum
2    C     92  Koc
0    A     88  Del

**sort by multiple columns**

In [ ]:
df.sort_values(["city","marks"])

  name  marks city
0    A     88  Del
2    C     92  Koc
3    D     98  Mum
1    B     76  Pun

**sort_index()**<br>
**reset_index()**

In [ ]:
df.sort_index()

  name  marks city
0    A     88  Del
1    B     76  Pun
2    C     92  Koc
3    D     98  Mum

In [ ]:
df.sort_index(ascending=False)

  name  marks city
3    D     98  Mum
2    C     92  Koc
1    B     76  Pun
0    A     88  Del

In [ ]:
df.reset_index() # resets the index position

   index name  marks city
0      0    A     88  Del
1      1    B     76  Pun
2      2    C     92  Koc
3      3    D     98  Mum

In [ ]:
df.reset_index(drop=True) # equal to sort_index

  name  marks city
0    A     88  Del
1    B     76  Pun
2    C     92  Koc
3    D     98  Mum

**groupby() and aggregate functions**

In [ ]:
a = df[df["name"]>'B']["marks"].mean()
a

np.float64(95.0)

In [ ]:
df.groupby("name")["marks"].mean()

name
A    88.0
B    76.0
C    92.0
D    98.0
Name: marks, dtype: float64

In [ ]:
df.groupby("name")["marks"].count()

name
A    1
B    1
C    1
D    1
Name: marks, dtype: int64

In [ ]:
df.groupby(["name","city"]).count()

           marks
name city
A    Del       1
B    Pun       1
C    Koc       1
D    Mum       1

In [ ]:
df.groupby(["name","city"])["marks"].count()

name  city
A     Del     1
B     Pun     1
C     Koc     1
D     Mum     1
Name: marks, dtype: int64

**multiple aggregate functions**

In [ ]:
# df.groupby("department")['salary'].agg(['mean','max','min'])

# so, groupby groups repetitive (same rows) rows together into a summary,
# row based on an aggregate function

# Aggregate Functions - Calculate on a set of values and give a single values.