<a href="https://colab.research.google.com/github/muhxz3/Ecommerce-Sales-Analysis/blob/main/Ecommerce_sales_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# loaing the dataset
import pandas as pd
data = pd.read_csv("Day8_Ecommerce_Sales_Dataset.csv")
data

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

In [ ]:
# displaying top 5 rows
data.head()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [ ]:
# displaying bottom 5 rows
data.tail()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

In [ ]:
# displaying random 5 rows
data.sample(5)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
92,1093,2026-05-16,Aisha Mir,Hyderabad,South,Sports,Cricket Bat,4,2499,15,8496.60,4.5,Cash on Delivery
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card
49,1050,2026-03-10,Ishita Gupta,Srinagar,North,Clothing,T-Shirt,4,799,0,3196.00,3.8,Net Banking
30,1031,2026-01-04,Rohan Mehta,Ahmedabad,West,Sports,Yoga Mat,1,899,15,764.15,4.1,Credit Card

**Data info**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    object
 2   Customer          100 non-null    object
 3   City              100 non-null    object
 4   Region            100 non-null    object
 5   Category          100 non-null    object
 6   Product           100 non-null    object
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    object
dtypes: float64(2), int64(4), object(7)
memory usage: 10.3+ KB

In [ ]:
data.isna().sum()

Order_ID            0
Order_Date          0
Customer            0
City                0
Region              0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Rating              0
Payment_Method      0
dtype: int64

**Observation** - It was found that there was no null values or missing values

**Data Extraction and Filtering**

In [ ]:
data["Customer"] # selecting the customers

0        Kabir Ali
1     Aditya Verma
2       Sara Ahmed
3        Kabir Ali
4      Priya Menon
          ...
95    Aditya Verma
96      Arjun Nair
97       Yusuf Dar
98     Hiba Sheikh
99       Kabir Ali
Name: Customer, Length: 100, dtype: object

In [ ]:
# Displays the details of orders that were sold at the max Quantity compared to all the items
data[(data["Quantity"] == max(data["Quantity"]))]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
24,1025,2026-01-02,Rohan Mehta,Chennai,South,Sports,Football,5,799,0,3995.00,5.0,UPI
26,1027,2026-05-02,Sara Ahmed,Chandigarh,North,Sports,Football,5,799,15,3395.75,4.6,Net Banking
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
41,1042,2026-06-20,Manya Rao,Kochi,South,Home & Kitchen,Water Bottle,5,699,0,3495.00,4.2,UPI
46,1047,2026-02-07,Sana Malik,Bengaluru,South,Electronics,Wireless Mouse,5,899,15,3820.75,4.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
66,1067,2026-05-21,Karan Joshi,Mumbai,West,Books,The Alchemist,5,499,10,2245.50,4.0,Net Banking
71,1072,2026-05-03,Aarav Sharma,Jaipur,North,Sports,Yoga Mat,5,899,10,4045.50,4.3,Debit Card
72,1073,2026-06-04,Sara Ahmed,Kolkata,East,Books,Atomic Habits,5,599,15,2545.75,4.6,Credit Card
80,1081,2026-01-30,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,5,1499,15,6370.75,4.0,Debit Card
83,1084,2026-06-19,Aisha Mir,Kolkata,East,Electronics,Wireless Mouse,5,899,10,4045.50,3.8,Cash on Delivery
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
90,1091,2026-06-26,Hiba Sheikh,Kochi,South,Books,Atomic Habits,5,599,0,2995.00,5.0,Net Banking
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

In [ ]:
# Displaying different products
data["Product"].unique()

array(['Wireless Headphones', 'Running Shoes', 'Power Bank',
       'Mechanical Keyboard', 'Smart Watch', 'The Alchemist',
       'Water Bottle', 'Hoodie', 'Electric Kettle', 'Jacket',
       'Coffee Maker', 'Cricket Bat', 'Mixer Grinder', 'Yoga Mat',
       'Football', 'Python Programming', 'Atomic Habits', 'T-Shirt',
       'Dumbbell Set', 'Machine Learning Basics', 'Wireless Mouse',
       'Jeans', 'Data Science Handbook'], dtype=object)

In [ ]:
# Product with the highest unit price
data[data["Unit_Price"] == max(data["Unit_Price"])]["Product"].unique()

array(['Coffee Maker'], dtype=object)

**Coffee Maker** has the highest unit price.

In [ ]:
# Orders between Jan 2026 and April 2026
data[(data["Order_Date"] >= "2026-01-01") & (data["Order_Date"] <= "2026-04-30")]

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

In [ ]:
# Displaying customers and their cities who bought sports items and Displayed in Ascending order of the customer
data[data["Category"] == "Sports"][["Customer","City"]].sort_values(by="Customer")

        Customer        City
71  Aarav Sharma      Jaipur
1   Aditya Verma       Jammu
89  Aditya Verma     Lucknow
37  Aditya Verma        Pune
39  Aditya Verma   Ahmedabad
95  Aditya Verma       Kochi
92     Aisha Mir   Hyderabad
11    Aman Kumar  Chandigarh
22    Aman Kumar      Jaipur
52  Ananya Singh   Hyderabad
54    Arjun Nair     Chennai
13     Dev Patel      Jaipur
48  Ishita Gupta      Mumbai
59   Karan Joshi        Pune
58    Mehak Bhat     Chennai
82   Priya Menon       Jammu
81     Rahul Das       Jammu
20  Reyansh Jain  Chandigarh
30   Rohan Mehta   Ahmedabad
35   Rohan Mehta    Srinagar
24   Rohan Mehta     Chennai
55   Rohan Mehta    Srinagar
23   Rohan Mehta      Jaipur
16    Sana Malik   Hyderabad
26    Sara Ahmed  Chandigarh

In [ ]:
# Displaying avg of Total_Sales of each Category
data.groupby("Category")["Total_Sales"].mean()

Category
Books             1752.019048
Clothing          4930.585714
Electronics       4846.631579
Home & Kitchen    5396.661905
Sports            5441.058000
Name: Total_Sales, dtype: float64

In [ ]:
# Displaying sum of Total_Sales of each Cities
data.groupby("City")["Total_Sales"].sum().sort_values()

City
Bhubaneswar     6598.00
Srinagar       11778.60
Bengaluru      13524.30
Ahmedabad      14788.70
Jammu          16059.75
Kolkata        20169.00
Jaipur         25534.00
Delhi          30882.80
Chandigarh     34539.65
Kochi          37257.50
Mumbai         41457.80
Pune           41908.55
Lucknow        46194.65
Chennai        47493.20
Hyderabad      59076.45
Name: Total_Sales, dtype: float64

**Observation** :
<br>
-  Books Category has the least average Total_Sales whereas Sports Category has the highest average Total_Sales.
-  Hyderabad City has the highest(sum) total sales.

In [ ]:
# Products and their max sales
data.groupby("Product")["Total_Sales"].max().sort_values(ascending = False)

Product
Running Shoes              13995.00
Coffee Maker               12596.40
Cricket Bat                12495.00
Jacket                     10620.75
Mechanical Keyboard         9496.20
Dumbbell Set                9495.25
Mixer Grinder               8547.15
Smart Watch                 6598.00
Electric Kettle             6370.75
Hoodie                      6076.20
Wireless Headphones         5996.00
Data Science Handbook       4495.00
Wireless Mouse              4045.50
Yoga Mat                    4045.50
Football                    3995.00
Water Bottle                3495.00
Jeans                       3228.30
T-Shirt                     3196.00
Python Programming          2996.00
Atomic Habits               2995.00
Power Bank                  2398.00
The Alchemist               2245.50
Machine Learning Basics     1998.00
Name: Total_Sales, dtype: float64

**Observation** - Running Shoes has the highest Total_Sales

In [ ]:
# Payment method with Total_Sales
data.groupby("Payment_Method")["Total_Sales"].sum()

Payment_Method
Cash on Delivery     50123.30
Credit Card         106540.25
Debit Card           98064.90
Net Banking          96371.25
UPI                  96163.25
Name: Total_Sales, dtype: float64

**Observation** - Most sales amount are done through Credit card

<hr>
<b>Highest, Lowest, Total and Average Sales based on City</b>
<hr>

In [ ]:
data.groupby("City")["Total_Sales"].agg(["min","max","sum","mean"])

                 min       max       sum         mean
City
Ahmedabad     764.15   4497.00  14788.70  2464.783333
Bengaluru     711.55   5996.00  13524.30  3381.075000
Bhubaneswar  6598.00   6598.00   6598.00  6598.000000
Chandigarh    449.10   9496.20  34539.65  4317.456250
Chennai      1518.10   8922.45  47493.20  4749.320000
Delhi         948.10   9996.00  30882.80  5147.133333
Hyderabad    4497.00  13295.25  59076.45  8439.492857
Jaipur        799.00   8397.00  25534.00  3647.714286
Jammu         759.05   6076.20  16059.75  2676.625000
Kochi         449.10   9495.25  37257.50  4139.722222
Kolkata       899.10   6370.75  20169.00  2881.285714
Lucknow       539.10  12495.00  46194.65  7699.108333
Mumbai        679.15  13995.00  41457.80  5182.225000
Pune         1078.20   9495.25  41908.55  4190.855000
Srinagar     1188.30   3798.10  11778.60  2355.720000

In [ ]:
# City with highest Total_Sales
data[data["Total_Sales"] == max(data["Total_Sales"])]["City"].unique()

array(['Mumbai'], dtype=object)

In [ ]:
# Quantity sold where Total_Sales is max
data[data["Total_Sales"] == max(data["Total_Sales"])][["City","Quantity"]]

      City  Quantity
48  Mumbai         5

In [ ]:
# City with lowest Total Sales
data[data["Total_Sales"] == min(data["Total_Sales"])]["City"].unique()

array(['Kochi', 'Chandigarh'], dtype=object)

In [ ]:
# Quantity sold where Total_Sales is min
data[data["Total_Sales"] == min(data["Total_Sales"])][["City","Quantity"]]

          City  Quantity
5        Kochi         1
62  Chandigarh         1

<hr>
<b>Highest, Lowest, Total and Average Sales based on Category</b>
<hr>

In [ ]:
data.groupby("Category")["Total_Sales"].agg(["min","max","sum","mean"])

                    min       max        sum         mean
Category
Books            449.10   4495.00   36792.40  1752.019048
Clothing         679.15  10620.75   69028.20  4930.585714
Electronics     1708.10   9496.20   92086.00  4846.631579
Home & Kitchen  1188.30  12596.40  113329.90  5396.661905
Sports           759.05  13995.00  136026.45  5441.058000

In [ ]:
# Category with highest Total_Sales
data[data["Total_Sales"] == max(data["Total_Sales"])]["Category"].unique()

array(['Sports'], dtype=object)

In [ ]:
# Quantity sold where Total_Sales is max
data[data["Total_Sales"] == max(data["Total_Sales"])][["Category","Quantity"]]

   Category  Quantity
48   Sports         5

In [ ]:
# Category with lowest Total Sales
data[data["Total_Sales"] == min(data["Total_Sales"])]["Category"].unique()

array(['Books'], dtype=object)

In [ ]:
# Quantity sold where Total_Sales is min
data[data["Total_Sales"] == min(data["Total_Sales"])][["Category","Quantity"]]

   Category  Quantity
5     Books         1
62    Books         1

<hr>
<b>Highest, Lowest, Total and Average Sales based on Products</b>
<hr>

In [ ]:
data.groupby("Product")["Total_Sales"].agg(["min","max","sum","mean"])

                             min       max       sum         mean
Product
Atomic Habits             539.10   2995.00  11590.65  1931.775000
Coffee Maker             2974.15  12596.40  51610.25  7372.892857
Cricket Bat              4498.20  12495.00  41483.40  8296.680000
Data Science Handbook    4495.00   4495.00   4495.00  4495.000000
Dumbbell Set             1999.00   9495.25  30184.90  6036.980000
Electric Kettle          3822.45   6370.75  26382.40  5276.480000
Football                  759.05   3995.00  10307.10  2576.775000
Hoodie                   1599.00   6076.20   7675.20  3837.600000
Jacket                   7497.00  10620.75  47106.15  9421.230000
Jeans                    3228.30   3228.30   6456.60  3228.300000
Machine Learning Basics   899.10   1998.00   5694.30  1423.575000
Mechanical Keyboard      7497.00   9496.20  26489.40  8829.800000
Mixer Grinder            2999.00   8547.15  25341.55  6335.387500
Power Bank               2038.30   2398.00   6474.60  2158.200000
Python Programming        711.55   2996.00   7527.45  1881.862500
Running Shoes            2799.00  13995.00  41285.25  8257.050000
Smart Watch              3134.05   6598.00  15670.25  5223.416667
T-Shirt                   679.15   3196.00   7790.25  1558.050000
The Alchemist             449.10   2245.50   7485.00  1247.500000
Water Bottle             1188.30   3495.00   9995.70  1999.140000
Wireless Headphones      2998.00   5996.00  33877.40  4839.628571
Wireless Mouse           1708.10   4045.50   9574.35  3191.450000
Yoga Mat                  764.15   4045.50  12765.80  2127.633333

In [ ]:
# Product with highest Total_Sales
data[data["Total_Sales"] == max(data["Total_Sales"])]["Product"].unique()

array(['Running Shoes'], dtype=object)

In [ ]:
# Quantity sold where Total_Sales is max
data[data["Total_Sales"] == max(data["Total_Sales"])][["Product","Quantity"]]

          Product  Quantity
48  Running Shoes         5

In [ ]:
# Product with lowest Total Sales
data[data["Total_Sales"] == min(data["Total_Sales"])]["Product"].unique()

array(['The Alchemist'], dtype=object)

In [ ]:
# Quantity sold where Total_Sales is min
data[data["Total_Sales"] == min(data["Total_Sales"])][["Product","Quantity"]]

          Product  Quantity
5   The Alchemist         1
62  The Alchemist         1

<hr >

In [ ]:
# Count of customers from different regions
data["Region"].value_counts()

Region
North    38
South    30
West     24
East      8
Name: count, dtype: int64

**Note:** Most of the customers are from North

In [ ]:
data.groupby("Product")["Quantity"].sum().sort_values(ascending=False)

Product
Wireless Headphones        23
Atomic Habits              21
Jacket                     20
Electric Kettle            19
Cricket Bat                18
The Alchemist              17
Coffee Maker               16
Dumbbell Set               16
Yoga Mat                   16
Running Shoes              15
Water Bottle               15
Football                   14
Wireless Mouse             12
Python Programming         11
Mechanical Keyboard        11
T-Shirt                    10
Mixer Grinder               9
Power Bank                  6
Machine Learning Basics     6
Data Science Handbook       5
Hoodie                      5
Smart Watch                 5
Jeans                       4
Name: Quantity, dtype: int64

**Note : Wireless headphones** were sold the most

In [ ]:
# Customers and orders
data.groupby(["Customer","City","Region"])["Order_ID"].value_counts()

Customer       City        Region  Order_ID
Aarav Sharma   Jaipur      North   1072        1
               Kochi       South   1075        1
Aditya Verma   Ahmedabad   West    1040        1
               Delhi       North   1070        1
                                   1080        1
                                              ..
Vivaan Kapoor  Chandigarh  North   1039        1
               Kolkata     East    1087        1
Yusuf Dar      Bengaluru   South   1098        1
Zoya Khan      Kolkata     East    1065        1
               Pune        West    1037        1
Name: count, Length: 100, dtype: int64

**Key Observation** - Every Customers are unique